# Generated by Django 4.1.7 on 2023-03-04 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_app.board')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_app.board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=250)),
                ('priority', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2023, 3, 4, 17, 47, 2, 890462))),
                ('deadline', models.DateTimeField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_app.category')),
                ('mark_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kanban_app.mark')),
            ],
        ),
    ]
