# Generated by Django 4.1.7 on 2023-03-04 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='board_id',
            new_name='board',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='mark_id',
            new_name='mark',
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 4, 18, 4, 46, 733357)),
        ),
    ]
