# Generated by Django 4.1.7 on 2023-03-08 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_rename_board_id_category_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('yellow', 'yellow'), ('green', 'green'), ('red', 'red'), ('light-blue', 'light-blue'), ('blue', 'blue'), ('purple', 'purple'), ('violet', 'violet'), ('orange', 'orange')], default='red', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 13, 57, 21, 936893)),
        ),
    ]
