# Generated by Django 4.1.7 on 2023-06-01 12:43

from django.db import migrations, models
import django.utils.timezone
import kanban_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_alter_task_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=kanban_app.models.default_deadline),
        ),
    ]
